apiVersion: v1
baseDomain: ibm-jti.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    vsphere:
      cpus: 1
      coresPerSocket: 8
      memoryMB: 16384
      osDisk:
        diskSizeGB: 120
  replicas: 2
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    vsphere:
      cpus: 1
      coresPerSocket: 4
      memoryMB: 8192
      osDisk:
        diskSizeGB: 60
  replicas: 3
metadata:
  creationTimestamp: null
  name: ocp-lab
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    apiVIP: 192.168.201.200
    cluster: JTI-Lab-Cluster
    datacenter: JTI-Lab
    defaultDatastore: LUN_RAID5
    ingressVIP: 192.168.201.201
    network: JTILab - VM Network
    password: StSud1rm4n@2023!
    username: ibm-ricky
    vCenter: jti-lab-vcenter.ibm-jti.com
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfN2Q4YzA3NDM4YTMyNDEyODkyMDZkM2I1MDUzZjUzZGI6U0ZGNFpUOFhDM05LUUtTWktTWVUyMkdPTUI0WU9QTTkzV05QUEpTMDBBSzIzUkdTTlA1VDc0MUJMS1g5NjQxTw==","email":"ivtah.djauhar@ibm.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfN2Q4YzA3NDM4YTMyNDEyODkyMDZkM2I1MDUzZjUzZGI6U0ZGNFpUOFhDM05LUUtTWktTWVUyMkdPTUI0WU9QTTkzV05QUEpTMDBBSzIzUkdTTlA1VDc0MUJMS1g5NjQxTw==","email":"ivtah.djauhar@ibm.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLWU2MTkxMTM0LTQ5NTAtNDQ2OC1hMjVkLTI1N2FhMzFkNDZlMTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmhORGxqWW1abE1ESTNaRE0wWldJeE9HWTFOVEpoTVRZM1pqSmxPVGszTkNKOS5nZVNOTEpMUFk2UEEwV1Y0VWFOU3FSNmJUNlFGVTZLU1ZMLUgxbHNWVG1hR2hwS3Z2V0ZRcW9Rc1N0U2xScGhLZU5kc2p1eXB0VjAxWVB4d2l1NjUyNlV3aUY5ZmxYRjAyM2NyOG5hSjB2VUg2MDJORDRFZ0JyUlFSYm42X0stN3F3dU1SVzBxLWhSbFpybzBTX1hjT2pyR2RGRXJ3ZWFkLWlld3lJb1lWcnV3MlhiR29fMFF1Uk5BUmpydlN4Z3F6Zm9lU1ZyY1VONm45bWtqd2xVQ2k1QzRkVUtEMFYySmRKcG56REJ0YkhDUzlBS0EwOEhTY2dmSW9XcnBqV3J3N0tlTlVRZFpJa01BdzB4TWNSWFNvdVhfbW94ZTROeVdVTzIzdGxjY1lmYnlCY3FDbldZZjNrN2txQUNwd05XRElXbWtJUFkwYW1kX3RmR1JNczh0cHhZWDFFdGJTbkhsVlZyOWpNVG8zNExkcU5haFkySkdsMmFXTUZ4NUVmb19iNkJtSGRrLU9TYUlETWxDUVVwNkozQnM3WjVFT25xSmR0bW4xYVhDVzlWaV9FbHhiVXF3QWd2bnAxSU9oZFUyVGtqLTVBWFpQTmJMYzhHQjZWZkhhaHVaVlN3clRlVkdNbHVwQUNFQmdvMk5OV2JTTG9uZTQ2aVZxNjRKbHNLeV9xamw4S2NUQkZCS1VpMFJIbllBMHVKR0VFcERqdjZ0TS1sa0F2X285SmhrVl9BNDJqVlZTUEFtZmpBS1NVbGIyTnVTT0U2UVgtdDdtSXp5NmkzNHM1SEVucnl5dkE2ZmIxaFhlUWo4VHJVYmNHZXlYMUd2VExud19WVXlla21BaGdOcVc0QUV4a3g0MHh0QndTNVJITGowMGhFZ2RsUjhLVHRYRFM5akJJTQ==","email":"ivtah.djauhar@ibm.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWU2MTkxMTM0LTQ5NTAtNDQ2OC1hMjVkLTI1N2FhMzFkNDZlMTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmhORGxqWW1abE1ESTNaRE0wWldJeE9HWTFOVEpoTVRZM1pqSmxPVGszTkNKOS5nZVNOTEpMUFk2UEEwV1Y0VWFOU3FSNmJUNlFGVTZLU1ZMLUgxbHNWVG1hR2hwS3Z2V0ZRcW9Rc1N0U2xScGhLZU5kc2p1eXB0VjAxWVB4d2l1NjUyNlV3aUY5ZmxYRjAyM2NyOG5hSjB2VUg2MDJORDRFZ0JyUlFSYm42X0stN3F3dU1SVzBxLWhSbFpybzBTX1hjT2pyR2RGRXJ3ZWFkLWlld3lJb1lWcnV3MlhiR29fMFF1Uk5BUmpydlN4Z3F6Zm9lU1ZyY1VONm45bWtqd2xVQ2k1QzRkVUtEMFYySmRKcG56REJ0YkhDUzlBS0EwOEhTY2dmSW9XcnBqV3J3N0tlTlVRZFpJa01BdzB4TWNSWFNvdVhfbW94ZTROeVdVTzIzdGxjY1lmYnlCY3FDbldZZjNrN2txQUNwd05XRElXbWtJUFkwYW1kX3RmR1JNczh0cHhZWDFFdGJTbkhsVlZyOWpNVG8zNExkcU5haFkySkdsMmFXTUZ4NUVmb19iNkJtSGRrLU9TYUlETWxDUVVwNkozQnM3WjVFT25xSmR0bW4xYVhDVzlWaV9FbHhiVXF3QWd2bnAxSU9oZFUyVGtqLTVBWFpQTmJMYzhHQjZWZkhhaHVaVlN3clRlVkdNbHVwQUNFQmdvMk5OV2JTTG9uZTQ2aVZxNjRKbHNLeV9xamw4S2NUQkZCS1VpMFJIbllBMHVKR0VFcERqdjZ0TS1sa0F2X285SmhrVl9BNDJqVlZTUEFtZmpBS1NVbGIyTnVTT0U2UVgtdDdtSXp5NmkzNHM1SEVucnl5dkE2ZmIxaFhlUWo4VHJVYmNHZXlYMUd2VExud19WVXlla21BaGdOcVc0QUV4a3g0MHh0QndTNVJITGowMGhFZ2RsUjhLVHRYRFM5akJJTQ==","email":"ivtah.djauhar@ibm.com"}}}'
sshKey: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIID6dwedRfCG72ycu4PcGvK3hYNNIlIIw50aLSZn/HNd root@okd4-lab-services
