apiVersion: v1
baseDomain: example.local
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  replicas: 0  # Must be set to 0 for User Provisioned Installation as worker nodes will be manually deployed.
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ocp  # OCP Cluster Name
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16 
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    cluster: Server5
    datacenter: <datacenter-name>
    folder: "<folder structure complete path>"
    network: 1010p
    password: "supersecret"
    username: chandra@example.local
    vCenter: <vCenter hostname or IP address>
publish: External
pullSecret: ''
sshKey: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKBMNEg9CCHRG2Y9A9n30tBENcTwVzoNWnPd7pyBuMgV root@ocp-bastion.ocp.example.local
